packages:
  - 'packages/*'
  - 'apps/*'
verifyDepsBeforeRun: false
allowBuilds:
  '@firebase/util': true
  esbuild: true
  protobufjs: true
  re2: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - eve@0.24.6
  - '@goldlabelapps/prospects@3.2.8 || 3.2.9'
  - '@goldlabelapps/agent-layer@3.2.8'
  - '@goldlabelapps/uberedux@3.2.8'
  - '@goldlabelapps/flash@3.2.8'
  - '@goldlabelapps/theme@3.2.8'
